apiVersion: v2
name: as-vdb-grpc
description: A Helm chart for AS Vector Database gRPC services
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - tibco
  - activespaces
  - vectordb
  - grpc
  - documentstore
  - vectorstore
maintainers:
  - name: TIBCO BNL ATS Team
home: https://github.com/tibco/as-vdb-grpc
sources:
  - https://github.com/tibco/as-vdb-grpc