apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dockling.fullname }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5001
      protocol: TCP
  selector:
    app: {{ .Values.dockling.fullname }}
