{{- if .Values.ftlserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "as-vdb-grpc.fullname" . }}-ftlserver
  namespace: {{ include "as-vdb-grpc.namespace" . }}
  labels:
    {{- include "as-vdb-grpc.labels" . | nindent 4 }}
    app.kubernetes.io/component: ftlserver
spec:
  type: {{ .Values.ftlserver.service.type }}
  ports:
    - port: {{ .Values.ftlserver.service.port }}
      targetPort: {{ .Values.ftlserver.service.targetPort }}
      protocol: TCP
      name: ftl
  selector:
    {{- include "as-vdb-grpc.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ftlserver
{{- end }}