{{- if .Values.ftlserver.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "as-vdb-grpc.fullname" . }}-ftlserver
  namespace: {{ include "as-vdb-grpc.namespace" . }}
  labels:
    {{- include "as-vdb-grpc.labels" . | nindent 4 }}
    app.kubernetes.io/component: ftlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "as-vdb-grpc.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ftlserver
  template:
    metadata:
      labels:
        {{- include "as-vdb-grpc.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ftlserver
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "as-vdb-grpc.serviceAccountName" . }}
      containers:
        - name: ftlserver
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "as-vdb-grpc.imageRepository" (dict "root" . "image" .Values.ftlserver.image) }}:{{ include "as-vdb-grpc.imageTag" (dict "tag" .Values.ftlserver.image.tag "defaultTag" .Values.global.asVersion) }}
          imagePullPolicy: {{ .Values.ftlserver.image.pullPolicy }}
          args:
            - "-c"
            - "{{ .Values.ftlserver.command.configPath }}"
            - "-n"
            - "{{ .Values.ftlserver.command.name }}"
            {{- if .Values.ftlserver.command.authProviders }}
            {{- end }}
            {{- if .Values.ftlserver.command.licenseServerUrl }}
            - "--license"
            - "{{ .Values.ftlserver.command.licenseServerUrl }}"
            {{- end }}
          ports:
            - name: ftl
              containerPort: {{ .Values.ftlserver.service.targetPort }}
              protocol: TCP
          {{- if or .Values.ftlserver.config.ftlDevYaml .Values.ftlserver.config.ftlUsersConf .Values.ftlserver.config.licenseKeyFile .Values.persistence.enabled }}
          volumeMounts:
            {{- if .Values.ftlserver.config.ftlDevYaml }}
            - name: config
              mountPath: /config/ftl-dev.yaml
              subPath: ftl-dev.yaml
              readOnly: true
            {{- end }}
            {{- if .Values.ftlserver.config.ftlUsersConf }}
            - name: config
              mountPath: /config/ftlusers.conf
              subPath: ftlusers.conf
              readOnly: true
            {{- end }}
            {{- if .Values.ftlserver.config.licenseKeyFile }}
            - name: license
              mountPath: /config/AS-VECTORDB_ANY.bin
              subPath: AS-VECTORDB_ANY.bin
              readOnly: true
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.ftlserver.resources | nindent 12 }}
      {{- if or .Values.ftlserver.config.ftlDevYaml .Values.ftlserver.config.ftlUsersConf .Values.ftlserver.config.licenseKeyFile .Values.persistence.enabled }}
      volumes:
        {{- if or .Values.ftlserver.config.ftlDevYaml .Values.ftlserver.config.ftlUsersConf }}
        - name: config
          configMap:
            name: {{ include "as-vdb-grpc.fullname" . }}-config
        {{- end }}
        {{- if .Values.ftlserver.config.licenseKeyFile }}
        - name: license
          secret:
            secretName: {{ include "as-vdb-grpc.fullname" . }}-license
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "as-vdb-grpc.fullname" . }}-data
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}