{{- if .Values.ftlserver.config.licenseKeyFile }}
{{- $licenseContent := .Files.Get .Values.ftlserver.config.licenseKeyFile }}
{{- if $licenseContent }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "as-vdb-grpc.fullname" . }}-license
  namespace: {{ include "as-vdb-grpc.namespace" . }}
  labels:
    {{- include "as-vdb-grpc.labels" . | nindent 4 }}
type: Opaque
data:
  AS-VECTORDB_ANY.bin: {{ $licenseContent | b64enc }}
{{- end }}
{{- end }}